### ISSUE TITLE
Can't complete the process

### ISSUE THREAD

**Issue by dedalus2000** [ssinyagin/pcengines-apu-debian-cd#1]
I have tried to build the installation CD image many times, but every time I'm not able to complete the process.
Here the last logs

```
....
Reading in package information for amd64:
  Done: Read details of 522 packages for amd64
WARNING: no translated descriptions found for wheezy/main
WARNING: no translated descriptions found for wheezy/non-free
Starting to lay out packages into images:
  Adding the required directories
  Generating the image label and volume id
  Adding .disk/base_components
  Adding .disk/cd_type
  Adding udeb/base includes/excludes
WARNING: Unable to read UDEB_EXCLUDE file /home/eolo/test/apu/pcengines-apu-debian-cd/tmp//debian-cd/data/wheezy/amd64_netinst_udeb_exclude
  Adding docs to CD1
  Extracting FAQ on CD1
  Adding installtools
ERROR: package installation-guide-amd64 not found.
  Adding common docs on CD1
  Adding Release files
  Trying to add upgrade* directories
  (Optionally) making the image bootable for amd64:
    Running tools/boot/wheezy/boot-amd64 1 /home/eolo/test/apu/pcengines-apu-debian-cd/tmp//cd-build/wheezy/CD1
E: No packages found
  Adding tools to CD1
  Using ISOLINUX boot-disks image on CD1
`boot1/isolinux/g2ldr' -> `boot1/g2ldr'
`boot1/isolinux/g2ldr.mbr' -> `boot1/g2ldr.mbr'
`boot1/isolinux/setup.exe' -> `boot1/setup.exe'
`boot1/isolinux/win32-loader.ini' -> `boot1/win32-loader.ini'
  gtk/vmlinuz identical to ../vmlinuz. Linking
  Adding EFI boot code for amd64 on CD1
Using older EFI command line for xorriso 0
Starting new "amd64" CD 1 at /home/eolo/test/apu/pcengines-apu-debian-cd/tmp//debian-cd/wheezy/CD1
  Specified size for this image: 650MiB CD, 332031 2K-blocks maximum
  Starting the md5sum.txt file
  Placing packages into image 1
xorriso 1.2.2 : RockRidge filesystem manipulator, libburnia project.

  Checking base is installable for amd64
  Found all files needed for debootstrap for all binary arches
  Finishing off the Release file
  Finishing off md5sum.txt
xorriso 1.2.2 : RockRidge filesystem manipulator, libburnia project.

  CD 1 (not) filled with 522 packages, 101088 blocks, 207028224 bytes
Finished: 522 packages placed
including description: /home/eolo/test/apu/pcengines-apu-debian-cd/profiles/apu64.description
simple-cdd: extra files for simple-cdd
ERROR: missing required packages from profile default:  simple-cdd-profiles
WARNING: missing optional packages from profile default:  grub type-handling
ERROR: missing required packages from profile apu64:  firmware-realtek firmware-brcm80211 firmware-atheros firmware-ralink
ERROR: missing required packages from profile apu64:  firmware-realtek firmware-brcm80211 firmware-atheros firmware-ralink
```

Which can be the problem? I have installed each missing packed in the local wheezy distribution (from which I'm running the build process), but it doesn't help.
I can attach the full log text

Thanks for you help

**Comment by ssinyagin** [comment]
what OS is your machine running? It has to be a Wheezy host. As far as I tried, the script fails under Squeeze or ubuntu.

**Comment by ssinyagin** [comment]
also sometimes it gets stuck over the garbage left in tmp/, so you need to delete tmp/ contents.

**Comment by dedalus2000** [comment]
It is clear wheezy
Here my source.list

```
deb http://http.debian.net/debian wheezy-backports main
deb [arch=amd64,i386] http://download.virtualbox.org/virtualbox/debian wheezy contrib
deb [arch=amd64,i386]   http://www.deb-multimedia.org wheezy main non-free
deb [arch=amd64,i386] http://ftp.debian.org/debian/ wheezy main non-free contrib
deb-src http://ftp.debian.org/debian/ wheezy main non-free contrib
deb [arch=amd64,i386]  http://security.debian.org/ wheezy/updates main
deb-src http://security.debian.org/ wheezy/updates main
```

I had the problem since the beginning: I followed the instruction, so after the "git clone" there is no "tmp" folder.
I try again deleting the tmp folder, and also I will do a test on another wheezy installation
I'll let you know

**Comment by dedalus2000** [comment]
I have the same problem on the same wheezy machine. Could the problem be the i386 arch.?

On the new one it is all ok. The source.list is

```
deb http://ftp.debian.org/debian/ wheezy main non-free contrib
deb-src http://ftp.debian.org/debian/ wheezy main non-free contrib
deb http://security.debian.org/ wheezy/updates main contrib non-free
deb-src http://security.debian.org/ wheezy/updates main contrib non-free
```

The new iso works like a sharm, I have just installed it.
Thanks!

**Comment by ssinyagin** [comment]
strange, I tested it on i386 host, and it worked. Probably some packages
failed to download while it retrieved them from the mirror?

**Comment by dedalus2000** [comment]
Beh, yes, it seems. I have a log.txt with all the output, I put it on pastebin:
http://pastebin.com/UWFWN8m8

For example:

```
W: Failed to fetch file:/home/eolo/test/apu/pcengines-apu-debian-cd/tmp//mirror/dists/wheezy/main/binary-i386/Packages  File not found

W: Failed to fetch file:/home/eolo/test/apu/pcengines-apu-debian-cd/tmp//mirror/dists/wheezy/non-free/binary-i386/Packages  File not found

W: Failed to fetch file:/home/eolo/test/apu/pcengines-apu-debian-cd/tmp//mirror/dists/wheezy/main/debian-installer/binary-i386/Packages  File not found
```

**Comment by ssinyagin** [comment]
alright, so we can close the ticket :)
just in case, here are some related articles in my blog. I also got a new 3G modem that I'm going to test:
https://txlab.wordpress.com/tag/pcengines/

**Comment by strixaluco** [comment]
Hi! Thank you for this installer, but I am stuck with similar issue as well.
Log is here: https://physicle.com/view.php?id=f_q6bs0m
First I was trying to build image for amd64 under amd64 host, then I tried to build for both amd64 and x86 under x86 VM, but also with these errors. Also I tried to build for x86 under my main amd64 host. No luck. 
Searching in the internet led me to this bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=687355. But apparently it's not my case, as simple-cdd version in Wheezy is 0.3.15, while affected versions of simple-cdd were 0.3.13 and lower.

Do you have some ideas?

**Comment by ssinyagin** [comment]
@strixaluco the error says that the Debian mirror is broken. Are you using the original mirror URLs as specified in config, or some other specific mirror? Does your host have a reliable access to that mirror? 
It could also be that CDN points to an incomplete mirror, but it's quite rare.

**Comment by strixaluco** [comment]
Yes, I'm using original mirror and config file is intact. I am in China right now and I also had concerns about reliability of access, so I tried with VPN, but it didn't help. I should have mentioned it before. 
DNS poisoning also occurs here, so I made several attempts with provider's DNS, Google's public DNS and DNS from VPN provider as well. Unfortunately, also without success.

**Comment by ssinyagin** [comment]
before re-trying, delete the tmp/ subfolder. Sometimes the garbage left from unsuccsessful builds gets the script stuck.

**Comment by strixaluco** [comment]
Sure, I did that each time.
 Here is my sources.list:

```
deb http://ftp.cn.debian.org/debian/ wheezy main contrib non-free  
deb-src http://ftp.cn.debian.org/debian/ wheezy main contrib non-free 

deb http://ftp.cn.debian.org/debian/ wheezy-updates main contrib non-free 
deb-src http://ftp.cn.debian.org/debian/ wheezy-updates main contrib non-free 

deb http://security.debian.org/ wheezy/updates main contrib non-free 
deb-src http://security.debian.org/ wheezy/updates main contrib non-free 

deb http://ftp.cn.debian.org/debian wheezy-backports main contrib non-free 
```

**Comment by ssinyagin** [comment]
I assume your machine (where you execute the builder) is Debian Wheezy?
There are known problems with other distributions like Ubuntu.

**Comment by strixaluco** [comment]
Exactly. Both host and VM guest are Debian Wheezy 7.8 with all recent updates. Host is amd64, VM guest is x86

**Comment by strixaluco** [comment]
I also tried to substitute all the mirrors with `http://http.debian.net/debian/` but it didn't work

**Comment by ssinyagin** [comment]
I tried it on a freshly upgraded VM, and it really breaks with the same
error...
Looks like something is really broken with the latest updates. I'll try to
dig deeper during the week.

**Comment by strixaluco** [comment]
Thank you

**Comment by ssinyagin** [comment]
here's where it breaks:
file (= 5.11-2+deb7u6): FAILED
  file (= 5.11-2+deb7u6) depends on missing:
- libmagic1 (= 5.11-2+deb7u6)
  dnsutils (= 1:9.8.4.dfsg.P1-6+nmu2+deb7u3): FAILED
  dnsutils (= 1:9.8.4.dfsg.P1-6+nmu2+deb7u3) depends on missing:
- libbind9-80 (= 1:9.8.4.dfsg.P1-6+nmu2+deb7u3)

these packages are superceeded by security updates, but the dependent packages are not updated.

I'm testing a possible workaround now

**Comment by ssinyagin** [comment]
disabling security mirror doesn't help, so something fundamental is broken...

**Comment by strixaluco** [comment]
I wish to assist somehow and it will be nice if you can point out how can I do that. Not sure if my knowledge is enough, though.

**Comment by ssinyagin** [comment]
here's an image that I found on my old build machine. It should work fine:
http://www.k-open.com/s/pcengines/debian-7.7-amd64-CD-1.iso

**Comment by strixaluco** [comment]
Thanks, but I meant that I'd like to contribute)
Image is downloading, but I cannot try it out yet. Hope that during this week it will be possible and I will write here back.

**Comment by ssinyagin** [comment]
the issue looks like a fundamental failure with Debian 7.8.
But after upgrading the host system to Jessie, the tool has generated an ISO image. I didn't test it yet. If you have time, please try:  http://www.k-open.com/s/pcengines/debian-8.0-amd64-CD-1.iso

**Comment by strixaluco** [comment]
Thank you, I shared the link with the person, who is going to install the image. He hadn't free time to do that yet.

**Comment by ssinyagin** [comment]
ha ha, the issue is solved. The link `ftp://cdn.debian.net/debian` stopped working, that's why it's breaking. The build worked after setting `wget_debian_mirror="ftp://ftp.ch.debian.org/debian/"` -- or you can select any working FTP mirror near you. I will update the scripts later.

**Comment by ssinyagin** [comment]
commit 8128642a8fa639194b5a052d782412172f3482f0

**Comment by strixaluco** [comment]
This looks curious. I don't remember for sure, but it seems that initially I was trying also with another mirrors. Hope that tomorrow I will have time to try.

**Comment by ssinyagin** [comment]
I also placed an ISO in releases, check that out

**Comment by strixaluco** [comment]
Some news here.
Now image is building successfully! There were some minor errors in the log, but in overall it's fine. I can provide full log if there is a need.
About installation - everything worked fine with previous 7.7 image. Thank you so much.

**Comment by ssinyagin** [comment]
Did you also try the image in releases section? All my boards are out in
the field.

**Comment by strixaluco** [comment]
Sorry, but no. The person, who was helping me, already had 7.7 build and I didn't want to bother him more.

**Comment by higkoo** [comment]
I meet the same error :

> Finished: 929 packages placed
> purging /home/higkoo/jessie-iso/tmp//extras
> including description: /home/higkoo/jessie-iso/profiles/bilibili.description
> simple-cdd: extra files for simple-cdd
> WARNING: missing optional packages from profile default:  console-tools
> ERROR: missing required packages from profile bilibili:  vim
> WARNING: missing optional packages from profile bilibili:  texlive-latex-extra-doc texlive-latex-recommended-doc texlive-pictures-doc texlive-pstricks-doc time tk tk8.6 unicon-imc2 unzip vim vim-runtime vprerex w3m wamerican whois zhcon

**Comment by ssinyagin** [comment]
I just tried it on a fresh Jessie system and built a Jessie ISO image without problems. I'm uploading it to https://github.com/ssinyagin/pcengines-apu-debian-cd/releases

Probably your host had problems downloading the packages from the debian repository.
