### ISSUE TITLE
Crash on Software selection

### ISSUE THREAD

**Issue by jaroslavsafranek** [ssinyagin/pcengines-apu-debian-cd#13]
Hi,

I try install Strech binnary on APU over CDROM, but it's crashed in step of Software selection.
Can you confirm thet this ISO is working well?

Regards Jaroslav

**Comment by ssinyagin** [comment]
Hi, I tested it several times and it went fine. Maybe your USB drive us
faulty.

**Comment by rschwebel** [comment]
Do you see the same issue I reported in https://github.com/ssinyagin/pcengines-apu-debian-cd/issues/11 ?

**Comment by ssinyagin** [comment]
It might be related to how httpredir.debian.org works. I noticed that sometimes it points to an IPv6-only site, and if your LAN doesn't have IPv6 connectivity, apt-get crashes. Could you try specifying the mirror explicitly?

**Comment by ssinyagin** [comment]
oh, looks like I need to change the URL anyway
https://wiki.debian.org/DebianGeoMirror

**Comment by jaroslavsafranek** [comment]
It might be related to how httpredir.debian.org works - Yes it's possible. An the end I install Jessie from your binnary and upgrade to Strech over apt-get. Then I try install Proxmox and have errors over  httpredir.debian.org, when I change it to ftp.cz.debian.org was all ok.

**Comment by jaroslavsafranek** [comment]
Yes, it's problem with mirror, can you change it in your binnary?

**Comment by ssinyagin** [comment]
yes I will. As you see, that method is obsoleted, and now it's deb.debian.org

**Comment by ssinyagin** [comment]
guys, I pushed f3220aa0 and uploaded a new IOS in Releases. Please check if it works better for you. So far, worked fine with me.

**Comment by jaroslavsafranek** [comment]
Thank you.

**Comment by ssinyagin** [comment]
@Jarek, does it work now for you?
