### ISSUE TITLE
Mirror needs to be signed

### ISSUE THREAD

**Issue by ffries** [ssinyagin/pcengines-apu-debian-cd#14]
Nice project, thanks.
Do you know how to overcome this error?

> 2017-08-02 22:25:02 ERROR build/debian-cd exited with code 2
> 2017-08-02 22:25:02 ERROR Last 5 lines of standard error:
> 2017-08-02 22:25:02 ERROR build/debian-cd: E: The repository 'file:/home/xxx/pc-engines/pcengines-apu-debian-cd/tmp/mirror stretch Release' is not signed.
> 2017-08-02 22:25:02 ERROR build/debian-cd: E: The repository 'file:/home/xxx/pc-engines/pcengines-apu-debian-cd/tmp/mirror stretch Release' is not signed.
> 2017-08-02 22:25:02 ERROR build/debian-cd: xorriso 1.4.6 : RockRidge filesystem manipulator, libburnia project.
> 2017-08-02 22:25:02 ERROR build/debian-cd: Can't open Packages file /home/xxx/pc-engines/pcengines-apu-debian-cd/tmp/cd-build/stretch/CD1/dists/stretch/main/binary-amd64/Packages : No such file or directory
> 2017-08-02 22:25:02 ERROR build/debian-cd: make: *** [image-trees] Erreur 2
> 2017-08-02 22:25:02 ERROR build/debian-cd exited with code 2, full log can be found in /home/xxx/pc-engines/pcengines-apu-debian-cd/tmp/log/build-debian-cd
>

**Comment by ssinyagin** [comment]
you need to create your own PGP key and sign your repository with it. You also need to import this key into APT. But that's only theory, I never tried it with build-simple-cdd.

Here I wrote instructions for a completely different project, but it explains the PGP key creation and signing:  https://freeswitch.org/confluence/display/FREESWITCH/Building+debs+for+other+architectures

If you end up in a repeatable and stable process, please send me your steps, and I'll update the README.

**Comment by ffries** [comment]
Thanks. In fact, debian-cd should sign its own repository. I don't know where the problem comes from and I spent already hours on it. What version of Debian would you recommend for building an installer. I understand this should be stable for stable installer. I was running SID in LXC. Might be an explanation. Will get back to you.

**Comment by ffries** [comment]
Confirmed. IK can build Strech CD from a Stretch host. The bug happens when trying to build a strech installer CD from a Debian SID host. So I am closing this bug.

**Comment by ssinyagin** [comment]
but it's written explicitly in README that the build machine must have the same release as the target CD

**Comment by ffries** [comment]
Yes, you were completely right.

**Comment by ssinyagin** [comment]
I added a ./build script that selects the OS release from the build host. Also see the updated README,
