### ISSUE TITLE
The ext4 file system creation in partition #1 of SCSI1 (0,0,0) (sda)  failed

### ISSUE THREAD

**Issue by ipexia** [ssinyagin/pcengines-apu-debian-cd#15]
Hello   
I add ther error, on install from your ISO file Debian 9.1.

My conf is:
- APU3a2
- msata SSD 32Go on mPCIe 3 (J14) (formated and tried with or without partition)

Doy ou have any idea?

Regards

`   lqqqqqqqqqqqqqqqqqqqqqqqu [!!] Partition disks tqqqqqqqqqqqqqqqqqqqqqqqqk
   x                                                                       x
   x                    Failed to create a file system                     x
   x The ext4 file system creation in partition #1 of SCSI1 (0,0,0) (sda)  x
   x failed.                                                               x
   x                                                                       x
   x     <Go Back>                                          <Continue>     x
   x                                                                       x
   mqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj

<Tab> moves; <Space> selects; <Enter> activates buttons `

**Comment by ssinyagin** [comment]
hi, first please check if the boot loader sees your SSD drive. You press (as far as I remember) F10, and it prompts you to boot from a media. It should show you your USB stick and the mSATA drive.

Another problem might be a presence of other USB or SATA devices. Then the behavior is not defined. 

There's also "manual" branch which disables as much automation as possible, and it should allow you select the target media. But I'm not fully happy with it, so it's not released yet.

**Comment by ipexia** [comment]
Hi,

Thank you for your answer. The system see the msata without problem:
Select boot device:

1. USB MSC Drive SanDisk Cruzer Fit 1.00
2. ata0-0: CHN mSATA01M 030 ATA-9 Hard-Disk (28626 MiBytes)
3. Payload [memtest]
4. Payload [setup]

And there are no other USB or sata device.

Can I remove the automatic partition and select from the ISO? I can try manualy to do this part.

Thank's
Olivier

**Comment by ipexia** [comment]
It can see the sda, and propose to change the partition.
`    x The partition tables of the following devices are changed:           x
    x    SCSI1 (0,0,0) (sda)                                               x
    x                                                                      x
    x The following partitions are going to be formatted:                  x
    x    partition #1 of SCSI1 (0,0,0) (sda) as ext4                       x
    x    partition #5 of SCSI1 (0,0,0) (sda) as ext4                       x
    x                                                                      x
    x Write the changes to disks?                                          x
    x                                                                      x
    x     <Yes>                                                   <No>     x
    x                                                                      x
`

When push yes -> failed

**Comment by ssinyagin** [comment]
can you try attaching it to another machine and write on it? It seems like a hardware problem. Or maybe you have another spare SSD drive, or SD card? You can install Voyage Linux on SD card, and try writing your SSD from there.

**Comment by ipexia** [comment]
I just be able to do the install. With a SSD in USB. I try with msata in usb mode, and after install I put it on pcei.

Very very strange...
I will try in few weeks with anoter msata, and keep you inform. Thank you for your help, I think you can close.

Olivier

**Comment by ssinyagin** [comment]
De rien  :)
