### ISSUE TITLE
Garbage on Screen

### ISSUE THREAD

**Issue by nebucaz** [ssinyagin/pcengines-apu-debian-cd#16]
Wrote binary Image to USB stick and got APU to boot from it. 
Only garbage is seen (after the text coming from APU BIOS was OK)
Using Screen screen /dev/cu.usbserial-FT8W1VHN 115200 8N1 on MacOS)
<img width="583" alt="bildschirmfoto 2017-09-24 um 20 13 16" src="https://user-images.githubusercontent.com/961682/30785278-0f2d5df8-a165-11e7-8630-c8f760b49f03.png">

**Comment by ssinyagin** [comment]
What happens if you let it run? The installer should launch automatically
after few seconds.

Can you try a different terminal emulator? Something compatible with vt100
or vt220 should work.

**Comment by nebucaz** [comment]
Letting it run keeps asking me questions that I can not answer. Switched Terminal to several emulations and Encodings with no luck. I guess, it has to do with the terminal settings, but I am curious, which combination will work. 

<img width="357" alt="bildschirmfoto 2017-09-24 um 21 47 46" src="https://user-images.githubusercontent.com/961682/30786159-191d1832-a172-11e7-8a10-90cab500ddc7.png">

**Comment by ssinyagin** [comment]
it's really strange, I never had any garbled input. Maybe your null-modem cable is broken?
If you see many questions, it might be the "manual" profile. The "apu64" asks only the hostname.

**Comment by nebucaz** [comment]
I tried to build the ISO, again: no luck:
<img width="827" alt="bildschirmfoto 2017-09-26 um 08 53 06" src="https://user-images.githubusercontent.com/961682/30846481-2aea1598-a298-11e7-8450-ba1c3d2232c1.png">

**Comment by ssinyagin** [comment]
Dnsutils is broken, I noticed that too. But it doesn't prevent the Debian
from installing. I have just installed two boxes about a week ago with this
issue.

**Comment by ssinyagin** [comment]
Ping me in Skype or telegram: ssinyagin
Maybe we do a screen sharing in the afternoon.

**Comment by nebucaz** [comment]
Tank you for your offer. I'm a few days off now. I'll give it another try and will let you know. Seems to be an issue on my side
