### ISSUE TITLE
Is fstrim scheduled too frequently?

### ISSUE THREAD

**Issue by d6e** [ssinyagin/pcengines-apu-debian-cd#17]
Hey, first off, thanks for publishing this. It really helps to have the trail blazed a bit. I just have a question/potential issue I was curious to hear some background on.

I noticed in `profiles/apu64.postinst` there's an hourly cronjob which runs fstrim on a daily basis. 
1. Why the extra logic for making an hourly cronjob daily? Why not just schedule it as a daily job?
2. Is there a reason for it being set to daily? The fstrim man pages appear to think weekly is sufficient. 

http://man7.org/linux/man-pages/man8/fstrim.8.html

**Comment by ssinyagin** [comment]
hi Danielle, thanks for the feedback.

1) this is intended to be for a box which may not be turned on all the time (I, for example, use them often as test devices, laying in my cupboard most of the time). So, a daily job would either need Anacron, which is an additional package, or this little hack to simulate anacron within the script. 

2) the default SSD that is shipper with PCEngines boards are 16GB, so the space is rather scarce. For a bigger SSD, the period could be longer. But in general, it doesn't hurt to run it daily. 

and what I usually do, is clone the project and create a task-specific profile, adding additional packages, SSH keys, and so on. There's also a way to add offline files, but I usually just retrieve them from my webserver. So, you're totally free to customize the profiles according to your needs.

**Comment by ssinyagin** [comment]
by the way, you may find something useful in my blog: https://txlab.wordpress.com/tag/pcengines/

Also I'll be giving a training on the APU platform, and I'll publish the slideshow as soon as it's ready.

**Comment by d6e** [comment]
Ah, that makes sense. Thanks for the context.
