### ISSUE TITLE
not work partition mssd

### ISSUE THREAD

**Issue by neidersun** [ssinyagin/pcengines-apu-debian-cd#18]
kann keine partition erstellt werden mit meiner mssd.

**Comment by ssinyagin** [comment]
Was für eine Model von SSD? Vielleicht es ist schon kaputt?
Gibt es anderen Komponenten im APU, zum Beispiel, einen zusätzlichen Speicher? Der Installer kann theoretisch falsch funktionieren falls es gibt andere Speicher ausser den SSD und Installations-USB Stick. Ab Mittwoch wir könnten auch telefonieren oder via Skype reden.

**Comment by neidersun** [comment]
Hallo. An der ssd kann es nicht liegen debian 9.3 geht zu installieren.

Am 29.12.2017 um 23:03 schrieb Stanislav Sinyagin <notifications@github.com<mailto:notifications@github.com>>:


Was für eine Model von SSD? Vielleicht es ist schon kaputt?
Gibt es anderen Komponenten im APU, zum Beispiel, einen zusätzlichen Speicher? Der Installer kann theoretisch falsch funktionieren falls es gibt andere Speicher ausser den SSD und Installations-USB Stick. Ab Mittwoch wir könnten auch telefonieren oder via Skype reden.

**Comment by ssinyagin** [comment]
Hallo, kannst du den "manual" Profile probieren? Dann bekommst du normalen Dialog für Disk Partitioning.
