### ISSUE TITLE
Read Error beim Booten nach der Installation

### ISSUE THREAD

**Issue by soernt** [ssinyagin/pcengines-apu-debian-cd#19]
Hallo,
ich beziehe mich auf die 9.1 Version:

Ich habe die Installation jetzt mit zwei verschiednen SSDs erfolglos und mehrfach probiert. Beide SSDs habe ich auf fehlerhafte Sektoren überprüfen lassen -> Es gibt keine.

- Die Installation läuft ohne erkennbaren Fehlermeldungen durch 
- Das System wird gestoppt. 
- Stromkabel abgezogen, 
- USB-Stick entfernt 
- wieder mit Strom versorgt
- das Boot-Menu erscheint
- "Booting from Hard Disk..." wird angezeigt
- Kurz darauf die Meldung"Read Error".

Wie komme ich dem Problem auf die Spur?

**Comment by soernt** [comment]
Das ist scheinbar ein Problem mit der BIOS Version der APU2. Nachdem ich die Version 4.0.17 (Lagacy) installiert habe, funktionierte auch der Start von Debian einwandfrei.

**Comment by ssinyagin** [comment]
danke, ich werde beim Hersteller melden.

**Comment by ssinyagin** [comment]
welche BIOS Version war mit der Fehler?

**Comment by soernt** [comment]
Hier gibt es eine Liste der BIOS-Versionen:
https://pcengines.github.io/

Ich hatte gestern die Version 4.6.9 aus der "Mainline release" Spalte verwendet und heute die 4.0.17 aus der "Legacy release" Spalte.

Die 4.0.17 und 4.6.9 wurden zeitgleich am 11.05.2018 veröffentlich. Mir sind die unterschiede zwischen den beiden Spalten nicht klar.

**Comment by ssinyagin** [comment]
hier ist ein Antwort vom Hersteller:

I just tried installing the OS using your ISO (https://github.com/ssinyagin/pcengines-apu-debian-cd/releases/download/9.1-20170801/debian-9.1-amd64-CD-1.iso) on an apu2 with the 4.6.9 coreboot BIOS.

    dd the ISO to an USB stick
    went through the auto-install process
    reboot to mSATA without any issues

Not sure what issues Sörnt Poppe ran into?

**Comment by soernt** [comment]
Danke für die Rückmeldung. Ich verwende den SATA Anschluss und nicht den mSATA - vielleicht ist das dass Problem?

Ich hatte das mit zwei Samsung SSDs probiert: Eine 840 EVO (256GB) und eine  840 PRO (256GB).
Bei beiden bekamm ich nach der Installation und dem Reboot gleich die Fehlermeldung "Read Error", Debian wurde erst garnicht geladen.

Das System läuft jetzt - ich bin zufrieden. Der Hersteller kann gerne mit mir Kontakt aufnehmen um genaueres in Erfahrung zu bringen.

**Comment by ssinyagin** [comment]
könnte Sie mir direkt auf ssinyagin@k-open.com mailen?
