### ISSUE TITLE
network by default bridged ?

### ISSUE THREAD

**Issue by ptorrent** [ssinyagin/pcengines-apu-debian-cd#23]
Hello,

I'm using apu1d4 , I'm able to see 3 eth (eth0/1/2) but It seems that all of them are bridged.

No bctcl configured, any ideas ?

**Comment by ssinyagin** [comment]
hi, they should not be bridged. They should be seen as 3 independent NICs. 

How do you come to conclusion about bridging?

**Comment by ptorrent** [comment]
![image](https://user-images.githubusercontent.com/6083644/123981914-ebed1c80-d9c2-11eb-95f2-0a46730d087e.png)

I'm able to join address X from Z (no ethernet cable on X and Y).  

It's looks like X + Z are bridged, and only Y is out of the bridge..

No ip forwarding enable,
No brctl 
No iptables

Very strange...

**Comment by ssinyagin** [comment]
it is indeed strange. We can try troubleshooting it together in a video call in about 5 hours. Ping me on telegram: ssinyagin

**Comment by ptorrent** [comment]
Sorry to have disturbed you. The mistake was on our side. Thank you for your quick reaction!
