### ISSUE TITLE
fstrim / and /boot return "the discard operation is not supported" whereas "fstrim -a -v" doesn't return anything

### ISSUE THREAD

**Issue by jmcroset** [ssinyagin/pcengines-apu-debian-cd#26]
Hi!

Not really an issue, probably something to do with my SSD, but I purchased it from pcengines, so I thinks it's kind of weird.
The return from hwinfo --disk is:
30: IDE 100.0: 10600 Disk
  [Created at block.245]
  Unique ID: 3OOL.QpVA+h5mR_5
  Parent ID: 7EWs.81yMhR119V4
  SysFS ID: /class/block/sda
  SysFS BusID: 1:0:0:0
  SysFS Device Link: /devices/pci0000:00/0000:00:11.0/ata2/host1/target1:0:0/1:0:0:0
  Hardware Class: disk
  Model: "APPLE HDD HTS545"
  Vendor: "APPLE"
  Device: "HDD HTS545"
  Revision: "B980"
  Serial ID: "TEG5193RKRBA9G"
  Driver: "ahci", "sd"
  Driver Modules: "ahci", "sd_mod"
  Device File: /dev/sda
  Device Number: block 8:0-8:15
  Geometry (Logical): CHS 60801/255/63
  Size: 976773168 sectors a 512 bytes
  Capacity: 465 GB (500107862016 bytes)
  Config Status: cfg=new, avail=yes, need=no, active=unknown
  Attached to: #24 (SATA controller)

As well, the size isn't correct; as far as I remember, I purchased:
msata16d    SSD M-Sata 16GB MLC Phison

Any clue why this behaviour / wrong detection ?

Best

JM

**Comment by cc32d9** [comment]
looks really weird, and it's not even SSD. It's a Hitachi 500GB hard disk. The kernel can't be wrong about it. Maybe indeed you connected an HDD to the PCengines board?

**Comment by ssinyagin** [comment]
looks really weird, and it's not even SSD. It's a Hitachi 500GB hard disk. The kernel can't be wrong about it. Maybe indeed you connected an HDD to the PCengines board?

**Comment by jmcroset** [comment]
Totally... I'll check next time I'm onsite. Thanks for the answer, keep you updated.

**Comment by jmcroset** [comment]
Verified, it has indeed an HD. So sorry about that!
