### ISSUE TITLE
200% useless, don't waste your time

### ISSUE THREAD

**Issue by petaflot** [ssinyagin/pcengines-apu-debian-cd#31]
first boot went more or less as expected, then the installer spontaneously repartitionned the USB flashdrive it was on instead of using the installed SD card.

Go back to M$ windows people, or don't publish stuff until it actually works

**Comment by ssinyagin** [comment]
LOL, are you actually able to read? It's stated in README, right in the beginning: This installation is only intended for an mSATA drive on the APU board. If you plan to boot from SD card, use Voyage Linux instead: http://linux.voyage.hk/
