### ISSUE TITLE
Push button support

### ISSUE THREAD

**Issue by jerome-arzel** [ssinyagin/pcengines-apu-debian-cd#5]
Is it possible to use the push button on the front to run a script with this Debian?

**Comment by ssinyagin** [comment]
I guess so, but I never tried. The button is connected to a GPIO interface, so you need to dig deeper into that.

**Comment by ssinyagin** [comment]
are you willing to contribute?

**Comment by jerome-arzel** [comment]
If needed yes.

I installed the gpio-apu2 module from [PC Engines](http://www.pcengines.ch/howto.htm#gpio), the /sys/class/gpio directory is missing. I think the kernel need to be recompiled with the CONFIG_GPIO_SYSFS option. I'll try to recompile the kernel myself, and after is it possible to change the kernel embeded in the installer?

**Comment by ssinyagin** [comment]
kernel is just a deb package, and it's specified in the preseed file:  
d-i base-installer/kernel/image string linux-image-amd64

so, if your new kernel is a valid Debian package, it's easy to integrate it in the installer, or simply install it after Debian is running on the box.

**Comment by jerome-arzel** [comment]
The 4.3 version of the kernel present in Debian seems to have CONFIG_GPIO_SYSFS option enabled, I think I'll upgrade it manually for now.

**Comment by ssinyagin** [comment]
when you finish testing, a pull request with README.GPIO will be appreciated

**Comment by ssinyagin** [comment]
how far are you with the progress? I have some requests for lighting/blinking the LED's on network status, so your input will be appreciated.

**Comment by jerome-arzel** [comment]
With the 4.3 version of the kernel, and an export of right IDs (see below), it is possible to know the value of the push button in /sys/class/gpio/gpio508/value.

To install and configure the module:

```
insmod gpio-apu2.ko
echo 508 > /sys/class/gpio/export
echo 509 > /sys/class/gpio/export
echo 510 > /sys/class/gpio/export
echo 511 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio508/direction
echo out > /sys/class/gpio/gpio509/direction
echo out > /sys/class/gpio/gpio510/direction
echo out > /sys/class/gpio/gpio511/direction
```

Unfortunatelly, polling seems not supported by this module, so /sys/class/gpio/gpio508/edge file does not exist and it is not possible to use poll() or select() to watch value changes. https://www.kernel.org/doc/Documentation/gpio/sysfs.txt

For the Debian Installer, I've done a fork at [Gnuside/pcengines-apu-debian-cd](https://github.com/Gnuside/pcengines-apu-debian-cd/commit/8c4af2053ef8728bf7f47d5c710fa93576e8ad96), but it is untested yet, I admit that using a kernel from backport is not a good solution.

**Comment by ssinyagin** [comment]
do you need to build gpio-apu2.ko from sources? I don't see it in https://packages.debian.org/jessie-backports/amd64/linux-image-4.5.0-0.bpo.2-amd64/filelist

**Comment by jerome-arzel** [comment]
I use gpio-apu2 from [here](http://www.pcengines.ch/howto.htm#gpio). Download gpio_apu2.tar.gz and compile it with a Makefile like this:

```
obj-m := gpio-apu2.o
SOURCE = $(subst .o,.c,$(obj-m))
MODULE = $(subst .o,.ko,$(obj-m))

all: $(MODULE)

$(MODULE): $(SOURCE)
        $(MAKE) -C /lib/modules/`uname -r`/build SUBDIRS=$(shell pwd) modules

clean:
        rm -f *.o *.ko .*.cmd .*.flags *.mod.c Module.symvers modules.order
        rm -rf .tmp_versions
```
