### ISSUE TITLE
Minor correction to README

### ISSUE THREAD

**Issue by reinerotto** [ssinyagin/pcengines-apu-debian-cd#6]
There is a cmd missing in the README:
....
...
git clone https://github.com/ssinyagin/pcengines-apu-debian-cd.git .
# -----------------> MISSING ------------------------------->

cd pcengines-apu-debian-cd-master
# ----------------------
## build the installation CD image (32bit or 64bit version). If you need
# to build another ISO image of a different architecture inside the same
# path, delete the contents of "tmp/" subdirectory.

build-simple-cdd --conf profiles/apu64.conf --dist jessie --force-root

**Comment by ssinyagin** [comment]
No it's not missing. You missed the dot at the end of the clone command.
